# Welcome to jekyll-vfolio theme!
#
# This config file is meant for settings that affect your whole website/blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Khidki
tagline: Intitiative by MITID Animation Alumni
email:
author: Ravi Gupta
description: KHIDKI is an initiative jointly by Animation Design Dept. & Animation Design Alumni to create a platform where Alumni & Industry experts bring in their expertise, skill, experiences & share with learners of MITID and fellow designers.
url: "https://khidki.club" # The base hostname & protocol for your website. Right now its set for local development. Please change it at the time of deployment.
baseurl: /
logo_small: assets/khidki_logo_small.png
banner: assets/banner.jpg
# The baseurl or the directory from where the site is hosted. Right now its set for the root directory. In case of GitHub Pages add '/repo-name' in front of 'baseurl:' without the quotes.
# For example -
# baseurl: /jekyll-vfolio

# Google Analytics
google_analytics: UA-171058063-1
google_analytics_4: G-HW6984RQVC


# Build settings
sass:
  sass_dir: css

# Social icons
show_social_icons: false
deviantart_username:
youtube_username:
instagram_username:

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
